"""Se crearon las tablas tiposDeFalla y tipodes de servicio

Revision ID: 08b5ab94a43b
Revises: d53a15020ec9
Create Date: 2025-03-13 19:50:17.596531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b5ab94a43b'
down_revision = 'd53a15020ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_de_falla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipoFalla', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('descripcion', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_de_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipoServicio', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('descripcion', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipos_de_servicio')
    op.drop_table('tipos_de_falla')
    # ### end Alembic commands ###
