"""Se cambio el campo de la contrasenia para que sea hash

Revision ID: 343d2d30cbee
Revises: 5943f0b265c7
Create Date: 2025-02-05 23:06:56.353301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343d2d30cbee'
down_revision = '5943f0b265c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
        batch_op.drop_column('contrasena_hash')

    # ### end Alembic commands ###
