"""Se agrego la tabla firmaOrdenDeTrabajo

Revision ID: 488584a3f4d4
Revises: 7ebe609050d6
Create Date: 2025-02-14 01:10:10.347049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488584a3f4d4'
down_revision = '7ebe609050d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmaOrdenDeTrabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idOrdenDeTrabajo', sa.Integer(), nullable=True),
    sa.Column('firmaCliente', sa.LargeBinary(), nullable=False),
    sa.Column('firmaTecnico', sa.LargeBinary(), nullable=False),
    sa.Column('fechaFirma', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('confirmacion', sa.Boolean(), nullable=False),
    sa.Column('comentario', sa.Text(collation='Latin1_General_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['idOrdenDeTrabajo'], ['ordenes_de_trabajo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firmaOrdenDeTrabajo')
    # ### end Alembic commands ###
