"""Se elimino la relacion con tecnico en la solicitud servicio

Revision ID: 4c994fac3acf
Revises: b360a9d75adc
Create Date: 2025-03-08 12:41:57.591681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c994fac3acf'
down_revision = 'b360a9d75adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_servicio', schema=None) as batch_op:
        batch_op.drop_constraint('FK__solicitud__idTec__2334397B', type_='foreignkey')
        batch_op.drop_column('idTecnico')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idTecnico', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK__solicitud__idTec__2334397B', 'tecnicos', ['idTecnico'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
