"""Nuevas tablas segun recomendaciones de leo v.2

Revision ID: 7ebe609050d6
Revises: ff377b2fed42
Create Date: 2025-02-14 01:01:49.063475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebe609050d6'
down_revision = 'ff377b2fed42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios_tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnicoId', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horaInicio', sa.Time(), nullable=False),
    sa.Column('horaFin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['tecnicoId'], ['tecnicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordenes_de_trabajo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechaInicio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duracion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('horaInicio', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('horaFin', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('prioridad', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=False))
        batch_op.add_column(sa.Column('comentario', sa.Text(collation='Latin1_General_CI_AS'), nullable=True))
        batch_op.add_column(sa.Column('fue_arreglado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('servicio_repuestos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo', sa.Float(), nullable=False))

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(collation='Latin1_General_CI_AS'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('servicio_repuestos', schema=None) as batch_op:
        batch_op.drop_column('costo')

    with op.batch_alter_table('ordenes_de_trabajo', schema=None) as batch_op:
        batch_op.drop_column('fue_arreglado')
        batch_op.drop_column('comentario')
        batch_op.drop_column('prioridad')
        batch_op.drop_column('horaFin')
        batch_op.drop_column('horaInicio')
        batch_op.drop_column('duracion')
        batch_op.drop_column('fechaInicio')

    op.drop_table('horarios_tecnicos')
    # ### end Alembic commands ###
