"""Se agrego el campo de email en usuario

Revision ID: 829ec1fc7ec2
Revises: 343d2d30cbee
Create Date: 2025-02-05 23:17:26.369345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829ec1fc7ec2'
down_revision = '343d2d30cbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
