"""Se agregaron los campos faltantes para la solicitud y se creo la tabla para los equipos de frio

Revision ID: 91238620622d
Revises: e41e0736c6f5
Create Date: 2025-02-22 15:06:58.198587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91238620622d'
down_revision = 'e41e0736c6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos_de_frio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segmento', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('marca', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('modelo', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('puerta', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # Paso 1: Agregar la columna nroCliente como nullable
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nroCliente', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=True))

    # Paso 2: Actualizar las filas existentes con un valor predeterminado
    op.execute("UPDATE clientes SET nroCliente = '00001' WHERE nroCliente IS NULL")

    # Paso 3: Cambiar la columna a NOT NULL
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('nroCliente', existing_type=sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False)

    with op.batch_alter_table('locales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entreCalle', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False))
        batch_op.add_column(sa.Column('horarioAtencion', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locales', schema=None) as batch_op:
        batch_op.drop_column('horarioAtencion')
        batch_op.drop_column('entreCalle')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('nroCliente')

    op.drop_table('equipos_de_frio')
    # ### end Alembic commands ###