"""Se agrego el campo razonSocial a cliente y se elimino el nroActivo

Revision ID: 91ac79547af2
Revises: 488584a3f4d4
Create Date: 2025-02-15 12:46:56.743924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ac79547af2'
down_revision = '488584a3f4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razonSocial', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False))
        batch_op.drop_column('nroActivo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nroActivo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('razonSocial')

    # ### end Alembic commands ###
