"""Se agregaron los campos nroSolicitud y fechaSolicitud a la tabla solicitudTrabajo

Revision ID: 99e08db57e57
Revises: 4c994fac3acf
Create Date: 2025-03-08 14:56:47.647177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e08db57e57'
down_revision = '4c994fac3acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechaSolicitud', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('nroSolicitud', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_servicio', schema=None) as batch_op:
        batch_op.drop_column('nroSolicitud')
        batch_op.drop_column('fechaSolicitud')

    # ### end Alembic commands ###
