"""Se agrego la relacion  solicitudServicio a orden de trabajo

Revision ID: b360a9d75adc
Revises: d64491839f4a
Create Date: 2025-03-08 12:36:49.505918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b360a9d75adc'
down_revision = 'd64491839f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_trabajo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_solicitud', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'solicitud_servicio', ['id_solicitud'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_de_trabajo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_solicitud')

    # ### end Alembic commands ###
