"""Se saco de activo el logo y se lo puso el dato en la tabla equipoDeFrio

Revision ID: d53a15020ec9
Revises: 99e08db57e57
Create Date: 2025-03-11 23:26:58.775145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53a15020ec9'
down_revision = '99e08db57e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.drop_column('logo')

    with op.batch_alter_table('equipos_de_frio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detallePuerta', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos_de_frio', schema=None) as batch_op:
        batch_op.drop_column('logo')
        batch_op.drop_column('detallePuerta')

    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
