"""Se agrego la tabla solicitudServicio

Revision ID: d64491839f4a
Revises: 91238620622d
Create Date: 2025-03-08 12:35:58.880227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64491839f4a'
down_revision = '91238620622d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=True),
    sa.Column('idActivo', sa.Integer(), nullable=True),
    sa.Column('idLocal', sa.Integer(), nullable=True),
    sa.Column('idTecnico', sa.Integer(), nullable=True),
    sa.Column('falla', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.ForeignKeyConstraint(['idActivo'], ['activos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idCliente'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idLocal'], ['locales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idTecnico'], ['tecnicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_servicio')
    # ### end Alembic commands ###
