"""Agregue el campo IP para la tabla auditoria

Revision ID: e41e0736c6f5
Revises: d4aac49fd889
Create Date: 2025-02-19 00:36:30.016587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41e0736c6f5'
down_revision = 'd4aac49fd889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccionIP', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_column('direccionIP')

    # ### end Alembic commands ###
