"""Creacion de modelo de datos con los consejos de leo  13/02

Revision ID: ff377b2fed42
Revises: 
Create Date: 2025-02-14 00:50:02.794684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff377b2fed42'
down_revision = None
branch_labels = None
depends_on = None


""" def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('cuit', sa.String(length=20, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('mail', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('telefono', sa.String(length=20, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('calle', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('numero', sa.String(length=10, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('localidad', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('provincia', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('nroActivo', sa.Integer(), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuit'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('especializacion', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('disponibilidad', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios_tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnicoId', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horaInicio', sa.Time(), nullable=False),
    sa.Column('horaFin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['tecnicoId'], ['tecnicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=20, collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('nombre', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('direccion', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('localidad', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('provincia', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('contacto', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('idLocal', sa.Integer(), nullable=True),
    sa.Column('modelo', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('marca', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('logo', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('descripcion', sa.Text(collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('nroSerie', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('nroActivo', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('voltaje', sa.Float(), nullable=True),
    sa.Column('poseeTierra', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idLocal'], ['locales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nroSerie')
    )
    op.create_table('ordenes_de_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('fecha_creada', sa.DateTime(), nullable=False),
    sa.Column('fecha_finalizada', sa.DateTime(), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('fechaInicio', sa.DateTime(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('horaInicio', sa.Time(), nullable=True),
    sa.Column('horaFin', sa.Time(), nullable=True),
    sa.Column('prioridad', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_tecnico', sa.Integer(), nullable=True),
    sa.Column('id_local', sa.Integer(), nullable=True),
    sa.Column('id_activo', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(collation='Latin1_General_CI_AS'), nullable=True),
    sa.Column('fue_arreglado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_activo'], ['activos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_local'], ['locales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_tecnico'], ['tecnicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('idActivo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idActivo'], ['activos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicio_repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_orden_de_trabajo', sa.Integer(), nullable=True),
    sa.Column('idRepuesto', sa.Integer(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['idRepuesto'], ['repuestos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_orden_de_trabajo'], ['ordenes_de_trabajo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idOrdenDeTrabajo', sa.Integer(), nullable=True),
    sa.Column('tipo_tarea', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
    sa.Column('descripcion', sa.Text(collation='Latin1_General_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['idOrdenDeTrabajo'], ['ordenes_de_trabajo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombreUsuario', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False))
        batch_op.add_column(sa.Column('tipoUsuario', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=False))
        batch_op.add_column(sa.Column('intentosLogin', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bloqueado', sa.Boolean(), nullable=True))
        batch_op.alter_column('contrasena_hash',
               existing_type=sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=255, collation='Latin1_General_CI_AS'),
               existing_nullable=False)
        batch_op.drop_column('nombre')
        batch_op.drop_column('email')
        batch_op.drop_column('tipo_usuario')
        batch_op.drop_column('cuitCuil')
 """
def upgrade():
    # Crear tabla usuarios PRIMERO
    op.create_table('usuarios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombreUsuario', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('contrasena_hash', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('tipoUsuario', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('estado', sa.Boolean(), nullable=True),
        sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
        sa.Column('intentosLogin', sa.Integer(), nullable=True),
        sa.Column('bloqueado', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Luego, crear clientes y tecnicos con FK hacia usuarios
    op.create_table('clientes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('cuit', sa.String(length=20, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('mail', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('telefono', sa.String(length=20, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('calle', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('numero', sa.String(length=10, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('localidad', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('provincia', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('latitud', sa.Float(), nullable=True),
        sa.Column('longitud', sa.Float(), nullable=True),
        sa.Column('nroActivo', sa.Integer(), nullable=True),
        sa.Column('idUsuario', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cuit'),
        sa.UniqueConstraint('mail')
    )

    op.create_table('tecnicos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('idUsuario', sa.Integer(), nullable=True),
        sa.Column('nombre', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('especializacion', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('disponibilidad', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    # Ahora se pueden crear locales y activos que dependen de clientes
    op.create_table('locales',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telefono', sa.String(length=20, collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('nombre', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('direccion', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('localidad', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('provincia', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('contacto', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('latitud', sa.Float(), nullable=True),
        sa.Column('longitud', sa.Float(), nullable=True),
        sa.Column('id_cliente', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('activos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('idLocal', sa.Integer(), nullable=True),
        sa.Column('modelo', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('marca', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('logo', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('descripcion', sa.Text(collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('nroSerie', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('nroActivo', sa.Integer(), nullable=True),
        sa.Column('estado', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=True),
        sa.Column('voltaje', sa.Float(), nullable=True),
        sa.Column('poseeTierra', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['idLocal'], ['locales.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nroSerie')
    )

    # Ahora, crear ordenes de trabajo que dependen de clientes, tecnicos, locales y activos
    op.create_table('ordenes_de_trabajo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('estado', sa.String(length=50, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('fecha_creada', sa.DateTime(), nullable=False),
        sa.Column('fecha_finalizada', sa.DateTime(), nullable=True),
        sa.Column('tipo_servicio', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('id_cliente', sa.Integer(), nullable=True),
        sa.Column('id_tecnico', sa.Integer(), nullable=True),
        sa.Column('id_local', sa.Integer(), nullable=True),
        sa.Column('id_activo', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['id_tecnico'], ['tecnicos.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['id_local'], ['locales.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['id_activo'], ['activos.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    # Finalmente, crear las tablas dependientes de ordenes de trabajo y activos
    op.create_table('repuestos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('descripcion', sa.String(length=255, collation='Latin1_General_CI_AS'), nullable=False),
        sa.Column('costo', sa.Float(), nullable=False),
        sa.Column('idActivo', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['idActivo'], ['activos.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('servicio_repuestos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('id_orden_de_trabajo', sa.Integer(), nullable=True),
        sa.Column('idRepuesto', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['idRepuesto'], ['repuestos.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['id_orden_de_trabajo'], ['ordenes_de_trabajo.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('servicios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('idOrdenDeTrabajo', sa.Integer(), nullable=True),
        sa.Column('tipo_tarea', sa.String(length=100, collation='Latin1_General_CI_AS'), nullable=False),
        sa.ForeignKeyConstraint(['idOrdenDeTrabajo'], ['ordenes_de_trabajo.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuitCuil', sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_usuario', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
        batch_op.alter_column('contrasena_hash',
               existing_type=sa.String(length=255, collation='Latin1_General_CI_AS'),
               type_=sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
        batch_op.drop_column('bloqueado')
        batch_op.drop_column('intentosLogin')
        batch_op.drop_column('tipoUsuario')
        batch_op.drop_column('nombreUsuario')

    op.drop_table('servicios')
    op.drop_table('servicio_repuestos')
    op.drop_table('repuestos')
    op.drop_table('ordenes_de_trabajo')
    op.drop_table('activos')
    op.drop_table('locales')
    op.drop_table('horarios_tecnicos')
    op.drop_table('tecnicos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
